version: '3.9'
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn fayzullo_platform.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - type: volume
        source: static_volume
        target: /furniture/staticfiles
      - type: volume
        source: media_volume
        target: /furniture/media
    expose:
      - 8000
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    ports:
      - 80:8000
    depends_on:
      - web
    volumes:
      - type: volume
        source: static_volume
        target: /furniture/staticfiles
      - type: volume
        source: media_volume
        target: /furniture/media

volumes:
  static_volume:
  media_volume:
